global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nestjs-app"
    static_configs:
      - targets: ["backend:5000"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
